config/routes.rb
#                edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#                     user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                                       PUT    /users(.:format)                                                                         devise/registrations#update
#                                       DELETE /users(.:format)                                                                         devise/registrations#destroy
#                                       POST   /users(.:format)                                                                         devise/registrations#create
#                              profiles GET    /profiles(.:format)                                                                      profiles#index
#                                       POST   /profiles(.:format)                                                                      profiles#create
#                           new_profile GET    /profiles/new(.:format)                                                                  profiles#new
#                          edit_profile GET    /profiles/:id/edit(.:format)                                                             profiles#edit
#                               profile GET    /profiles/:id(.:format)                                                                  profiles#show
#                                       PATCH  /profiles/:id(.:format)                                                                  profiles#update
#                                       PUT    /profiles/:id(.:format)                                                                  profiles#update
#                                       DELETE /profiles/:id(.:format)                                                                  profiles#destroy
#                          publications GET    /publications(.:format)                                                                  publications#index
#                                       POST   /publications(.:format)                                                                  publications#create
#                       new_publication GET    /publications/new(.:format)                                                              publications#new
#                      edit_publication GET    /publications/:id/edit(.:format)                                                         publications#edit
#                           publication PATCH  /publications/:id(.:format)                                                              publications#update
#                                       PUT    /publications/:id(.:format)                                                              publications#update
#                                       DELETE /publications/:id(.:format)                                                              publications#destroy
#                     monetary_accounts GET    /monetary_accounts(.:format)                                                             monetary_accounts#index
#                                       POST   /monetary_accounts(.:format)                                                             monetary_accounts#create
#                  new_monetary_account GET    /monetary_accounts/new(.:format)                                                         monetary_accounts#new
#                 edit_monetary_account GET    /monetary_accounts/:id/edit(.:format)                                                    monetary_accounts#edit
#                      monetary_account PATCH  /monetary_accounts/:id(.:format)                                                         monetary_accounts#update
#                                       PUT    /monetary_accounts/:id(.:format)                                                         monetary_accounts#update
#                                       DELETE /monetary_accounts/:id(.:format)                                                         monetary_accounts#destroy
#                        toggle_profile PUT    /toggle_profile(.:format)                                                                profiles#toggle_profile
#                                  root GET    /                                                                                        home#index
#                         appreciations GET    /profiles/:id/appreciations(.:format)                                                    appreciations#select
#                                coffee GET    /profiles/:id/appreciations/coffee(.:format)                                             appreciations#coffee
#                         coffee_create POST   /profiles/:id/appreciations(.:format)                                                    appreciations#coffee_create
#                                   hug GET    /profiles/:id/appreciations/hug(.:format)                                                appreciations#hug
#                                  hug2 GET    /profiles/:id/appreciations/hug2(.:format)                                               appreciations#hug2
#                                thanks GET    /profiles/:id/appreciations/thanks(.:format)                                             appreciations#thanks
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#   rails_mandrill_inbound_health_check GET    /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#health_check
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  devise_for :users
  resources :profiles
  resources :publications, except: :show
  resources :monetary_accounts, except: :show

  root to: "home#index"

  get '/user' => "profiles#edit", :as => :user_root

  put '/toggle_profile', to: 'profiles#toggle_profile'

  get 'profiles/:id/appreciations', to: 'appreciations#select', :as => 'appreciations'

  get 'profiles/:id/appreciations/coffee', to: 'appreciations#coffee', :as => 'coffee'
  post 'profiles/:id/appreciations', to: 'appreciations#coffee_create', :as => 'coffee_create'

  get 'profiles/:id/appreciations/hug', to: 'appreciations#hug_animation', :as => 'hug_animation'
  get 'profiles/:id/hug_appreciation', to: 'appreciations#hug_new', :as => 'hug_new'

app/models/appreciation.rb
# == Schema Information
#
# Table name: appreciations
#
#  id                :integer          not null, primary key
#  appreciation_kind :integer          not null
#  donor_fullname    :string           not null
#  donor_occupation  :string           not null
#  donor_message     :text             not null
#  coffees_quantity  :integer
#  hug_seconds       :float
#  user_id           :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
class Appreciation < ApplicationRecord
  belongs_to :user
  enum appreciation_kind: { hug: 0, coffee: 1 }
  validates :user, presence: true
  validates :appreciation_kind, :donor_fullname, :donor_occupation, :donor_message, presence: true
end

app/controllers/appreciations_controller.rb
class AppreciationsController < ApplicationController
  def select
    @profile = Profile.where('id = ?', params[:id]).first
  end

  def hug_animation
    @profile = Profile.where('id = ?', params[:id]).first
  end

  def hug_new
    @profile = Profile.where('id = ?', params[:id]).first
    @appreciation = Appreciation.new(hug_appreciation_params)
  end

  def hug_create
    @profile = Profile.where('id = ?', params[:id]).first
    @appreciation = Appreciation.new(hug_appreciation_params_create)
    @appreciation.assign_attributes(user_id: @profile.user_id, appreciation_kind: :hug)
    if @appreciation.save
      redirect_to thanks_url
    else
      redirect_to hug_new_url, alert2: "No se pudo crear el agradecimiento"
    end
  end

  def coffee
    @profile = Profile.where('id = ?', params[:id]).first
    @appreciation = Appreciation.new(user_id: @profile.user.id)
    @monetary_accounts = MonetaryAccount.where(user_id: @profile.user.id)
    @multipliers = @profile.multipliers
  end

  def coffee_create
    @profile = Profile.where('id = ?', params[:id]).first
    @appreciation = Appreciation.new(coffee_appreciation_params)
    @appreciation.assign_attributes(user_id: @profile.user_id, appreciation_kind: :coffee)
    if @appreciation.save
      redirect_to thanks_url
    else
      redirect_to coffee_url, alert2: "No se pudo crear el agradecimiento"
    end
  end

  def thanks
    @profile = Profile.where('id = ?', params[:id]).first
  end

  private

  def coffee_appreciation_params
    params.require(:appreciation).permit(:donor_fullname, :donor_occupation, :donor_message, :coffees_quantity)
  end

  def hug_appreciation_params
    params.permit(:hug_seconds)
  end

  def hug_appreciation_params_create
    params.permit(:donor_fullname, :donor_occupation, :donor_message, :hug_seconds)
  end
end

app/views/appreciations/_form_coffee.html.erb
<%= form_with model: @appreciation do |f| %>
  <div class="coffee-select-wrapper third-bkgrnd">
    <p class="primary-font your-data">¿Cuántos café?</p>
    <div class="coffee-info">
      <%= image_tag("coffee.svg", class: "coffee-img") %>
      <div class="multipliers-qty-wrapper">
        <div class="multiplier-btn" id="b1"><p class="primary-font" id="q1"><%= @multipliers[0][:quantity]%></p></div>
        <div class="multiplier-btn" id="b2"><p class="primary-font" id="q2"><%= @multipliers[1][:quantity]%></p></div>
        <div class="multiplier-btn" id="b3"><p class="primary-font" id="q3"><%= @multipliers[2][:quantity]%></p></div>
        <div class="multiplier-btn" id="b4"><p class="primary-font" id="q4"><%= @multipliers[3][:quantity]%></p></div>
      </div>
    </div>
    <div class="coffee-info"><p class="primary-font"><%= @profile.currency_sign %></p><p id="coffee-price" class="primary-font"><%= @profile.coffee_price %></p></div>
    <div><p class="primary-font">Total: <%= @profile.currency_sign %> <span id="total-amount" class="primary-font"></span></p></div>
  </div>
  <div class="third-bkgrnd accounts-header-wrapper"><p class="primary-font select-appreciation-header">Cuentas de <%= @profile.fullname %></p></div>
  <% if !@monetary_accounts.any? %>
    <div class="entity-data-wrapper third-bkgrnd"><p class="primary-font entity-data">El usuario no ha agregado ninguna cuenta aún.</p></div>
  <% end %>
  <% @monetary_accounts.each do |monetary_account| %>
    <div class="entity-data-wrapper third-bkgrnd">
      <% if monetary_account.entity.present? %>
        <p class="label primary-font entity-data">Entidad: <%= monetary_account.entity %></p>
      <% end %>
      <% if monetary_account.account_email.present? %>
        <p class="label primary-font entity-data">Email: <%= monetary_account.account_email %></p>
      <% end %>
      <% if monetary_account.account_number.present? %>
        <p class="label primary-font entity-data">Nro de cuenta: <%= monetary_account.account_number %></p>
      <% end %>  
      <% if monetary_account.identification.present? %>
        <p class="label primary-font entity-data">Identificación: <%= monetary_account.identification %></p>
      <% end %>    
      <% if monetary_account.account_kind.present? %>
        <p class="label primary-font entity-data">Tipo de cuenta: <%= monetary_account.account_kind %></p>
      <% end %>                             
    </div>
  <% end %>
  <div class="coffee-form-part third-bkgrnd">
    <p class="primary-font select-appreciation-header donor-data-header">Tus datos</p>
    <div class="field">
      <%= f.label :donor_fullname, 'Nombre', class: "label primary-font" %>
      <br>
      <%= f.text_field :donor_fullname, class: 'appreciation-form-field third-bkgrnd' %>
    </div> 
    <div class="field">
      <%= f.label :donor_occupation, 'Ocupación', class: "label primary-font" %>
      <br>
      <%= f.text_field :donor_occupation, class: 'appreciation-form-field third-bkgrnd' %>
    </div>     
    <div class="field">
      <%= f.label :donor_message, 'Mensaje de agradecimiento:', class: "label primary-font" %>
      <br>
      <%= f.text_area :donor_message, class: 'donor-field-field third-bkgrnd primary-font' %>
    </div>
    <%= f.hidden_field :coffees_quantity, id: "coffees-quantity"%>   
  </div>
  <div class="submit-btn-wrapper">
    <%= f.submit "Enviar", class: "submit primary-font second-bkgrnd" %>
  </div>
<% end %>

app/views/appreciations/coffee.html.erb
<%= render 'layouts/profile_header' %>
<div class="coffee-main-wrapper primary-bkgrnd">
  <div class= "back-wrapper">
    <%= link_to appreciations_path do%>
      <%= image_tag("Vector.svg", class: "vector-img") %>
      <span class= "back primary-font">Atrás</span>
    <% end %>
  </div>
  <div class="coffee-form-wrapper">
    <%= render 'form_coffee', object: @appreciation %>
  </div>
</div>

app/views/appreciations/hug.html.erb
<%= render 'layouts/profile_header' %>
<div class="coffee-main-wrapper primary-bkgrnd">
  <div class= "back-wrapper">
    <%= link_to appreciations_path do%>
      <%= image_tag("Vector.svg", class: "vector-img") %>
      <span class= "back primary-font">Atrás</span>
    <% end %>
  </div>
  <div class="select-header-container">
    <span class="select-appreciation-header primary-font">Formas de reconocer a <%=@profile.fullname%></span>
  </div>
  <div class="circle-container">
    <div class="third-bkgrnd" id="main-hug-circle">
      <div class="filling-circle" id="filling-circle"></div>
      <%= image_tag("hug.svg", class: "hug-img") %>
    </div>
  </div>
  <div>
    <p class="second-font hug-text">Abrazo de <span class="second-font"></span></p>
    <P class="primary-font hug-instruction">Mientras más tiempo lo presiones, mayor será el abrazo.</p>
  </div>
  <%= form_with model: @appreciation do |f| %>
    <%= f.hidden_field :coffees_quantity, id: "coffees-quantity"%> 
    <div class="submit-btn-wrapper">
      <%= f.submit "Siguiente", class: "submit primary-font second-bkgrnd" %>
    </div>
  <% end %> 
</div>

app/views/appreciations/hug_animation.html.erb
<%= render 'layouts/profile_header' %>
<div class="coffee-main-wrapper primary-bkgrnd">
  <div class= "back-wrapper">
    <%= link_to appreciations_path do%>
      <%= image_tag("Vector.svg", class: "vector-img") %>
      <span class= "back primary-font">Atrás</span>
    <% end %>
  </div>
  <div class="select-header-container">
    <span class="select-appreciation-header primary-font">Formas de reconocer a <%=@profile.fullname%></span>
  </div>
  <div class="circle-container">
    <div class="third-bkgrnd" id="main-hug-circle">
      <div class="filling-circle" id="filling-circle"></div>
      <%= image_tag("hug.svg", class: "hug-img", id: 'hug-img') %>
    </div>
  </div>
  <div>
    <div class="hug-text-wrapper">
      <p class="second-font hug-text">Abrazo de</p>
      <div class="timer-seconds-wrapper"><span class="second-font hug-text" id="timer-seconds">0.0</span></div>
      <p class="second-font hug-text">segundo(s)</p>
    </div>
    <P class="primary-font hug-instruction">Mientras más tiempo presiones el círculo, mayor será el abrazo.</p>
  </div>
  <%= form_with(url: hug_new_path, local: true, method: 'GET') do |f| %>
    <%= f.hidden_field :hug_seconds, id: "hug_seconds"%> 
    <div class="submit-btn-wrapper">
      <%= f.submit "Siguiente", class: "submit primary-font second-bkgrnd" %>
    </div>
  <% end %> 
</div>

app/views/appreciations/hug_new.html.erb
<%= render 'layouts/profile_header' %>
<div class="coffee-main-wrapper primary-bkgrnd">
  <div class= "back-wrapper">
    <%= link_to hug_animation_path do%>
      <%= image_tag("Vector.svg", class: "vector-img") %>
      <span class= "back primary-font">Atrás</span>
    <% end %>
  </div>
  <div class="coffee-form-wrapper">
    <%= form_with(url: hug_create_path) do |f| %>
      <div class="coffee-form-part third-bkgrnd">
        <p class="primary-font select-appreciation-header donor-data-header">Tus datos</p>
        <div class="field">
          <%= f.label :donor_fullname, 'Nombre', class: "label primary-font" %>
          <br>
          <%= f.text_field :donor_fullname, class: 'appreciation-form-field third-bkgrnd' %>
        </div> 
        <div class="field">
          <%= f.label :donor_occupation, 'Ocupación', class: "label primary-font" %>
          <br>
          <%= f.text_field :donor_occupation, class: 'appreciation-form-field third-bkgrnd' %>
        </div>     
        <div class="field">
          <%= f.label :donor_message, 'Mensaje de agradecimiento:', class: "label primary-font" %>
          <br>
          <%= f.text_area :donor_message, class: 'donor-field-field third-bkgrnd primary-font' %>
        </div>
        <%= f.hidden_field :hug_seconds, id: "hug_seconds", value: @appreciation.hug_seconds %>  
      </div>
      <div class="submit-btn-wrapper">
        <%= f.submit "Enviar", class: "submit primary-font second-bkgrnd" %>
      </div>
    <% end %>
  </div>
</div>

app/views/appreciations/select.html.erb
<%= render 'layouts/profile_header' %>
<div class="main primary-bkgrnd">
  <div class= "back-wrapper">
    <%= link_to profile_path do%>
      <%= image_tag("Vector.svg", class: "vector-img") %>
      <span class= "back primary-font">Atrás</span>
    <% end %>
  </div>
  <div class="select-appreciation-wrapper">
    <div class="select-appreciation-container">
      <div class="select-header-container">
        <span class="select-appreciation-header primary-font">Formas de reconocer a <%=@profile.fullname%></span>
      </div>
      <div class="flex-space" >
        <%= link_to coffee_path, class: "appreciation-link" do %>
          <div>
            <%= image_tag("coffee.svg", class: "coffee-img2") %>
          </div>
          <span class="primary-font">Café</span>
        <% end %>
        <%= link_to hug_animation_path, class: "appreciation-link" do %>
          <div>
            <%= image_tag("heart.svg", class: "heart-img") %>
          </div>
          <span class="primary-font">Abrazo</span>
        <% end %>
      </div>
    </div>
  </div>
  <div class="girl-img-wrapper">   
    <%= image_tag("girl-mobile.svg") %>
  </div>
  <div class="instruction-wrapper">
    <span class="primary-font instruction">Selecciona alguna de las dos opciones para continuar</span>
  </div>
</div>

app/views/appreciations/thanks.html.erb
<%= render 'layouts/profile_header' %>
<div class="thanks-container">
  <div class= "back-wrapper">
    <%= link_to profile_path do%>
      <%= image_tag("Vector.svg", class: "vector-img") %>
      <span class= "back primary-font">Atrás</span>
    <% end %>
  </div>
  <div class="thanks-img-wrapper">
    <%= image_tag("thanks.svg") %>  
  </div>
  <div class="thanks-wrapper"><span class="thanks second-font">¡Gracias!</span></div>
</div>